#!/bin/sh
if [ "$TERM" = "linux" ]; then
  /bin/echo -e "
  \e]P015161e
  \e]P1f7768e
  \e]P258ffc7
  \e]P3ffecb8
  \e]P482aaff
  \e]P5d2a6ef
  \e]P65ce1ff
  \e]P77586b3
  \e]P84e5b88
  \e]P9ff93a7
  \e]PA58ffc7
  \e]PBffecb8
  \e]PC82aaff
  \e]PDd2a6ef
  \e]PE5ce1ff
  \e]PFc5cde0
  "
  # get rid of artifacts
  clear
fi
